--------------------------------------------------------
--  File created - Tuesday-October-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SURVEY_MASTER
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_MASTER" 
   (	"SURVEY_ID" NUMBER(6,0), 
	"SURVEY_TITLE" VARCHAR2(50 BYTE), 
	"SURVEY_DESCRIPTION" VARCHAR2(100 BYTE), 
	"USER_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURVEY_DISTRIBUTION
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" 
   (	"DISTRIBUTION_ID" NUMBER(6,0), 
	"SURVEY_ID" NUMBER(6,0), 
	"DISTRIBUTION_DATE" TIMESTAMP (6), 
	"EXPIRY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURVEY_QUESTION_DETAILS
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" 
   (	"QUESTION_ID" NUMBER(6,0), 
	"SURVEY_ID" NUMBER(6,0), 
	"QUESTION_TEXT" VARCHAR2(500 BYTE), 
	"QUESTION_TYPE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURVEY_QUESTION_OPTIONS
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" 
   (	"OPTION_ID" NUMBER(6,0), 
	"QUESTION_ID" NUMBER(6,0), 
	"OPTION_DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURVEY_RESPONDENT_ANSWERS
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" 
   (	"USER_ID" NUMBER(6,0), 
	"DISTRIBUTION_ID" NUMBER(6,0), 
	"QUESTION_ID" NUMBER(6,0), 
	"OPTION_ID" NUMBER(6,0), 
	"ANSWER_TEXT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SURVEY_RESPONDENT_RELATIONSHIP
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_RELATIONSHIP" 
   (	"DISTRIBUTION_ID" NUMBER(6,0), 
	"USER_ID" NUMBER(6,0), 
	"RESPONSE_STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_MASTER
--------------------------------------------------------

  CREATE TABLE "JUL30JAVA2USER9"."USER_MASTER" 
   (	"USER_ID" NUMBER(6,0), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(2 BYTE), 
	"USER_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JUL30JAVA2USER9.SURVEY_MASTER
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.SURVEY_DISTRIBUTION
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.SURVEY_QUESTION_DETAILS
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.SURVEY_QUESTION_OPTIONS
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.SURVEY_RESPONDENT_ANSWERS
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.SURVEY_RESPONDENT_RELATIONSHIP
SET DEFINE OFF;
REM INSERTING into JUL30JAVA2USER9.USER_MASTER
SET DEFINE OFF;
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100001,'admin123','prabhjot ','singh','ad','y');
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100002,'20','pritika','sharma','ad','y');
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100003,'30','rahul','yyadav','rs','y');
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100004,'survey123','nafeez','virani','sy','y');
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100005,'duple123','anoop','jaswal','ad','y');
Insert into JUL30JAVA2USER9.USER_MASTER (USER_ID,USER_PASSWORD,FIRST_NAME,LAST_NAME,USER_TYPE,USER_ACTIVE) values (100006,'60','bbalaji','veerapan','rs','y');
--------------------------------------------------------
--  DDL for Index SURVEY_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUL30JAVA2USER9"."SURVEY_MASTER_PK" ON "JUL30JAVA2USER9"."SURVEY_MASTER" ("SURVEY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURVEY_DISTRIBUTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION_PK" ON "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" ("DISTRIBUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURVEY_QUESTION_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS_PK" ON "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SURVEY_QUESTION_OPTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS_PK" ON "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" ("OPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUL30JAVA2USER9"."USER_MASTER_PK" ON "JUL30JAVA2USER9"."USER_MASTER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SURVEY_MASTER
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_MASTER" ADD CONSTRAINT "SURVEY_MASTER_PK" PRIMARY KEY ("SURVEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_MASTER" MODIFY ("SURVEY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_MASTER" MODIFY ("SURVEY_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY_DISTRIBUTION
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" ADD CONSTRAINT "SURVEY_DISTRIBUTION_PK" PRIMARY KEY ("DISTRIBUTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" MODIFY ("DISTRIBUTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" MODIFY ("DISTRIBUTION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY_QUESTION_DETAILS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" ADD CONSTRAINT "SURVEY_QUESTION_DETAILS_PK" PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" MODIFY ("QUESTION_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" MODIFY ("QUESTION_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY_QUESTION_OPTIONS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" ADD CONSTRAINT "SURVEY_QUESTION_OPTIONS_PK" PRIMARY KEY ("OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" MODIFY ("OPTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" MODIFY ("OPTION_DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY_RESPONDENT_ANSWERS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" MODIFY ("ANSWER_TEXT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY_RESPONDENT_RELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_RELATIONSHIP" MODIFY ("RESPONSE_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_MASTER
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."USER_MASTER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."USER_MASTER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."USER_MASTER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."USER_MASTER" MODIFY ("USER_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "JUL30JAVA2USER9"."USER_MASTER" ADD CONSTRAINT "USER_MASTER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_MASTER
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_MASTER" ADD CONSTRAINT "SURVEY_MASTER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "JUL30JAVA2USER9"."USER_MASTER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_DISTRIBUTION
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" ADD CONSTRAINT "SURVEY_DISTRIBUTION_FK" FOREIGN KEY ("SURVEY_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_MASTER" ("SURVEY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_QUESTION_DETAILS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" ADD CONSTRAINT "SURVEY_QUESTION_DETAILS" FOREIGN KEY ("SURVEY_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_MASTER" ("SURVEY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_QUESTION_OPTIONS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" ADD CONSTRAINT "SURVEY_QUESTION_OPTIONS_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" ("QUESTION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_RESPONDENT_ANSWERS
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" ADD CONSTRAINT "SURVEY_ANS_DIST_FK" FOREIGN KEY ("DISTRIBUTION_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" ("DISTRIBUTION_ID") ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" ADD CONSTRAINT "SURVEY_ANS_OPTION_FK" FOREIGN KEY ("OPTION_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_QUESTION_OPTIONS" ("OPTION_ID") ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" ADD CONSTRAINT "SURVEY_ANS_QUES_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_QUESTION_DETAILS" ("QUESTION_ID") ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_ANSWERS" ADD CONSTRAINT "SURVEY_ANS_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "JUL30JAVA2USER9"."USER_MASTER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEY_RESPONDENT_RELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_RELATIONSHIP" ADD CONSTRAINT "SURVEY_REL_DISTRIBUTION_FK" FOREIGN KEY ("DISTRIBUTION_ID")
	  REFERENCES "JUL30JAVA2USER9"."SURVEY_DISTRIBUTION" ("DISTRIBUTION_ID") ENABLE;
 
  ALTER TABLE "JUL30JAVA2USER9"."SURVEY_RESPONDENT_RELATIONSHIP" ADD CONSTRAINT "SURVEY_REL_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "JUL30JAVA2USER9"."USER_MASTER" ("USER_ID") ON DELETE CASCADE ENABLE;
